In [1]:
import numpy as np

In [14]:
src = np.random.randn(2,3,4)

In [15]:
src

array([[[-0.24073602,  0.29582594, -0.89358431, -1.2500889 ],
        [ 0.9674155 , -0.76972606,  1.96793921, -0.37100844],
        [-0.09482699, -0.25512067,  0.99940552, -0.61228211]],

       [[-0.03388479,  0.23428422,  0.79640154, -1.09156635],
        [ 0.92903823,  0.81559569,  1.00159382, -0.02380573],
        [-1.07536343, -0.78823233,  0.13152073, -1.63611486]]])

In [16]:
src

array([[[-0.24073602,  0.29582594, -0.89358431, -1.2500889 ],
        [ 0.9674155 , -0.76972606,  1.96793921, -0.37100844],
        [-0.09482699, -0.25512067,  0.99940552, -0.61228211]],

       [[-0.03388479,  0.23428422,  0.79640154, -1.09156635],
        [ 0.92903823,  0.81559569,  1.00159382, -0.02380573],
        [-1.07536343, -0.78823233,  0.13152073, -1.63611486]]])

In [17]:
src=src[:,1:-1]

In [18]:
src

array([[[ 0.9674155 , -0.76972606,  1.96793921, -0.37100844]],

       [[ 0.92903823,  0.81559569,  1.00159382, -0.02380573]]])